//! Rust SDK for writing Convex backend functions that compile to WebAssembly.
//!
//! The SDK mirrors the TypeScript `convex` package's developer experience:
//!
//! ```ignore
//! use convex_sdk::{
//!     action, mutation, query, Context, ConvexError, Document,
//! };
//!
//! #[convex_functions]
//! pub mod functions {
//!     use convex_sdk::{query, Context, ConvexError, Document};
//!
//!     #[query]
//!     pub async fn get_user(ctx: Context, id: String) -> Result<Option<Document>, ConvexError> {
//!         ctx.db.get("users", &id).await
//!     }
//!
//!     #[mutation]
//!     pub async fn bump_counter(ctx: Context, by: i64) -> Result<i64, ConvexError> {
//!         let count = ctx.db.count("counters").await?;
//!         let next = count + by;
//!         Ok(next)
//!     }
//! }
//! ```
//!
//! Functions are exported to the backend through the `__convex_run` and
//! `__convex_functions` module exports generated by the `convex_functions`
//! attribute macro. The backend's `wasm_runner` crate executes them in a
//! sandboxed wasmtime instance.

pub mod rt;

pub use convex_sdk_macros::{
    action,
    convex_functions,
    http_action,
    mutation,
    query,
};
#[cfg(target_arch = "wasm32")]
pub use rt::dispatch;
pub use rt::FunctionDescriptor;

use serde::{
    Deserialize,
    Serialize,
};
use serde_json::Value as JsonValue;

/// A Convex value, a superset of JSON with tagged encodings for bytes,
/// int64s, and floats.
///
/// Plain JSON types can also be used directly in function signatures via
/// `serde`.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct ConvexValue(pub JsonValue);

impl ConvexValue {
    /// Wrap a plain JSON value.
    pub fn from_json(value: JsonValue) -> Self {
        Self(value)
    }

    /// The underlying JSON value.
    pub fn as_json(&self) -> &JsonValue {
        &self.0
    }

    /// Access a field of an object value.
    pub fn get(&self, field: &str) -> Option<ConvexValue> {
        self.0.get(field).cloned().map(ConvexValue::from_json)
    }
}

impl From<JsonValue> for ConvexValue {
    fn from(value: JsonValue) -> Self {
        Self(value)
    }
}

impl From<ConvexValue> for JsonValue {
    fn from(value: ConvexValue) -> Self {
        value.0
    }
}

/// A document stored in a Convex table.
///
/// The `value` is the complete document (including `_id` and
/// `_creationTime`); `id` and `creation_time` are convenience accessors.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct Document {
    /// The document's id, e.g. `"z34m4v0e2jk9qx8jq3q2jha25w"`.
    pub id: String,
    /// The document's creation time in milliseconds.
    pub creation_time: i64,
    /// The complete document value.
    pub value: ConvexValue,
}

impl Document {
    fn from_internal_json(value: JsonValue) -> Result<Self, ConvexError> {
        let id = value
            .get("_id")
            .and_then(JsonValue::as_str)
            .ok_or_else(|| ConvexError::new("Document is missing the _id field"))?
            .to_string();
        let creation_time = value
            .get("_creationTime")
            .and_then(JsonValue::as_f64)
            .map(|f| f as i64)
            .ok_or_else(|| {
                ConvexError::new(format!(
                    "Document is missing the _creationTime field: {value}"
                ))
            })?;
        Ok(Self {
            id,
            creation_time,
            value: ConvexValue(value),
        })
    }
}

/// An error raised by a Convex function.
///
/// The `code` field mirrors the TypeScript `ConvexError`'s error data.
#[derive(Clone, Debug, PartialEq)]
pub struct ConvexError {
    /// A human-readable message.
    pub message: String,
    /// An optional machine-readable error code.
    pub code: Option<String>,
}

impl ConvexError {
    /// Create a new error with a message and no code.
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
            code: None,
        }
    }

    /// Create a new error with a message and code.
    pub fn with_code(message: impl Into<String>, code: impl Into<String>) -> Self {
        Self {
            message: message.into(),
            code: Some(code.into()),
        }
    }
}

impl std::fmt::Display for ConvexError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.message)
    }
}

impl std::error::Error for ConvexError {}

impl From<String> for ConvexError {
    fn from(message: String) -> Self {
        Self::new(message)
    }
}

impl From<&str> for ConvexError {
    fn from(message: &str) -> Self {
        Self::new(message)
    }
}

impl From<rt::ConvexDbError> for ConvexError {
    fn from(error: rt::ConvexDbError) -> Self {
        Self {
            message: error.to_string(),
            code: None,
        }
    }
}

impl From<ConvexError> for JsonValue {
    fn from(error: ConvexError) -> Self {
        serde_json::json!({
            "message": error.message,
            "code": error.code,
        })
    }
}

/// The execution context passed to every function: database access, time,
/// randomness, and logging.
#[derive(Clone, Debug)]
pub struct Context {
    /// The database handle.
    pub db: Database,
}

impl Default for Context {
    fn default() -> Self {
        Self::new()
    }
}

impl Context {
    /// Create a new execution context.
    pub fn new() -> Self {
        Self {
            db: Database,
        }
    }

    /// The deterministic, virtual current time in milliseconds since the Unix
    /// epoch. Identical for every retry of the function.
    pub fn now(&self) -> i64 {
        rt::now_ms()
    }

    /// Deterministic random bytes, seeded per invocation so retries produce
    /// the same bytes.
    pub fn random_bytes(&self, len: usize) -> Vec<u8> {
        rt::random_bytes(len)
    }

    /// 32 deterministic random bytes, suitable for a secret or id.
    pub fn random(&self) -> [u8; 32] {
        let bytes = rt::random_bytes(32);
        bytes.try_into().expect("32 bytes")
    }

    /// Emit a log line, visible in the dashboard alongside function results.
    pub fn log(&self, message: impl AsRef<str>) {
        rt::log(message.as_ref());
    }
}

/// The database handle passed to functions.
#[derive(Clone, Debug, Default)]
pub struct Database;

impl Database {
    /// Fetch a single document by id. Returns `Ok(None)` if it does not
    /// exist.
    pub async fn get(
        &self,
        table: &str,
        id: &str,
    ) -> Result<Option<Document>, ConvexError> {
        let result = rt::db_call(
            rt::DB_GET,
            &serde_json::json!({ "table": table, "id": id }),
        )?;
        match result {
            JsonValue::Null => Ok(None),
            value => Ok(Some(Document::from_internal_json(value)?)),
        }
    }

    /// Insert a new document and return its id.
    pub async fn insert(
        &self,
        table: &str,
        value: ConvexValue,
    ) -> Result<String, ConvexError> {
        let result = rt::db_call(
            rt::DB_INSERT,
            &serde_json::json!({ "table": table, "value": value.0 }),
        )?;
        result
            .get("_id")
            .and_then(JsonValue::as_str)
            .map(str::to_string)
            .ok_or_else(|| ConvexError::new("db.insert returned no _id"))
    }

    /// Replace a document entirely. Returns the replaced document.
    pub async fn replace(
        &self,
        table: &str,
        id: &str,
        value: ConvexValue,
    ) -> Result<Document, ConvexError> {
        let result = rt::db_call(
            rt::DB_REPLACE,
            &serde_json::json!({ "table": table, "id": id, "value": value.0 }),
        )?;
        Document::from_internal_json(result)
    }

    /// Merge fields into a document. Returns the patched document.
    pub async fn patch(
        &self,
        table: &str,
        id: &str,
        value: ConvexValue,
    ) -> Result<Document, ConvexError> {
        let result = rt::db_call(
            rt::DB_PATCH,
            &serde_json::json!({ "table": table, "id": id, "value": value.0 }),
        )?;
        Document::from_internal_json(result)
    }

    /// Delete a document. Returns the deleted document.
    pub async fn delete(&self, table: &str, id: &str) -> Result<Document, ConvexError> {
        let result = rt::db_call(
            rt::DB_DELETE,
            &serde_json::json!({ "table": table, "id": id }),
        )?;
        Document::from_internal_json(result)
    }

    /// Count the documents in a table.
    pub async fn count(&self, table: &str) -> Result<i64, ConvexError> {
        let result = rt::db_call(rt::DB_COUNT, &serde_json::json!({ "table": table }))?;
        result
            .as_f64()
            .map(|f| f as i64)
            .ok_or_else(|| ConvexError::new("db.count returned a non-number"))
    }

    /// Fetch all documents in a table.
    ///
    /// Filters, indexes, and pagination are not yet supported; see
    /// `docs/wasm.md` for limitations.
    pub async fn query(&self, table: &str) -> Result<Vec<Document>, ConvexError> {
        let result = rt::db_call(rt::DB_QUERY, &serde_json::json!({ "table": table }))?;
        let documents = result
            .as_array()
            .ok_or_else(|| ConvexError::new("db.query returned a non-array"))?;
        documents
            .iter()
            .cloned()
            .map(Document::from_internal_json)
            .collect()
    }
}
